#!/bin/sh
# Render the Homebrew formula for a release, from the checksums `make dist`
# produced.
#
#   make dist VERSION=v0.2.0
#   make brew-formula VERSION=v0.2.0 > apm-registry.rb
#
# The formula points at the release assets rather than rebuilding from source,
# so what `brew install` puts on disk is byte-identical to what install.sh
# fetches — the digest a lockfile recorded stays the digest that is served.
#
# POSIX sh, like install.sh: /bin/sh is not bash on Debian or macOS.

set -eu

REPO="xgentic/agent-package-manager-registry"
BINARY="apm-registry"
DIST="${DIST:-dist}"

VERSION="${VERSION:-$(git describe --tags --exact-match 2>/dev/null || true)}"
[ -n "$VERSION" ] || {
	echo "brew-formula: no VERSION given and HEAD is not tagged" >&2
	exit 1
}

sums="${DIST}/SHA256SUMS"
[ -f "$sums" ] || {
	echo "brew-formula: ${sums} not found — run 'make dist VERSION=${VERSION}' first" >&2
	exit 1
}

# No `version` stanza: Homebrew scans it out of the tag in the download URL, and
# stating it as well is an audit failure.
#
# Look up one asset's digest, failing loudly rather than emitting a formula with
# an empty sha256 that would install anything at all.
digest() {
	d="$(awk -v want="$1" '$2 == want || $2 == "*" want { print $1 }' "$sums")"
	[ -n "$d" ] || { echo "brew-formula: no checksum for $1 in ${sums}" >&2; exit 1; }
	printf '%s' "$d"
}

url() {
	printf 'https://github.com/%s/releases/download/%s/%s-%s' "$REPO" "$VERSION" "$BINARY" "$1"
}

cat <<EOF
# Generated by scripts/brew-formula.sh — do not edit by hand.
# Regenerate with: make brew-formula VERSION=${VERSION}
class ApmRegistry < Formula
  desc "Self-hosted package registry server for the apm client"
  homepage "https://github.com/${REPO}"
  license "MIT"

  on_macos do
    on_arm do
      url "$(url darwin-arm64)"
      sha256 "$(digest "${BINARY}-darwin-arm64")"
    end
    on_intel do
      url "$(url darwin-amd64)"
      sha256 "$(digest "${BINARY}-darwin-amd64")"
    end
  end

  on_linux do
    on_arm do
      url "$(url linux-arm64)"
      sha256 "$(digest "${BINARY}-linux-arm64")"
    end
    on_intel do
      url "$(url linux-amd64)"
      sha256 "$(digest "${BINARY}-linux-amd64")"
    end
  end

  def install
    # One bare binary per platform, named for the platform it was built for.
    bin.install Dir["${BINARY}-*"].first => "${BINARY}"
  end

  service do
    run [opt_bin/"${BINARY}", "serve"]
    keep_alive true
    working_dir var/"${BINARY}"
    log_path var/"log/${BINARY}.log"
    error_log_path var/"log/${BINARY}.err.log"
    # Loopback on purpose: this build has no authentication, and a service that
    # starts at login must not put an open registry on every interface.
    environment_variables APM_REGISTRY_ADDR:     "127.0.0.1:3000",
                          APM_REGISTRY_DATA_DIR: var/"${BINARY}",
                          APM_REGISTRY_BASE_URL: "http://localhost:3000"
  end

  def caveats
    <<~CAVEATS
      This build has NO AUTHENTICATION. Every endpoint is open to anyone who can
      reach it, publish included. Keep it on loopback, a VPN, or behind a proxy
      that authenticates on its behalf.

      A fresh install has no repositories, and no HTTP route creates one:

        ${BINARY} repo create local --public

      Started with "brew services start ${BINARY}", it listens on 127.0.0.1:3000
      and keeps its data in #{var}/${BINARY}.
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/${BINARY} version")

    # Proves the pure-Go SQLite driver works on this machine, which is the part
    # a cross-compiled binary is most likely to get wrong.
    ENV["APM_REGISTRY_DATA_DIR"] = testpath/"data"
    system bin/"${BINARY}", "migrate"
    assert_path_exists testpath/"data/registry.db"
  end
end
EOF
